name: healpray
description: "HealPray - Your Daily Healing & Prayer Companion. An AI-powered emotional and spiritual wellness companion."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'
  flutter: ">=3.16.0"

dependencies:
  flutter:
    sdk: flutter

  # UI & Design
  cupertino_icons: ^1.0.6
  flutter_svg: ^2.0.9
  cached_network_image: ^3.3.1
  flutter_staggered_animations: ^1.1.1
  rive: ^0.12.4
  lottie: ^3.0.0
  animations: ^2.0.11
  flutter_animate: ^4.5.0
  shimmer: ^3.0.0

  # State Management & Architecture
  riverpod: ^2.4.9
  flutter_riverpod: ^2.4.9
  hooks_riverpod: ^2.4.9
  flutter_hooks: ^0.20.5

  # Navigation
  go_router: ^12.1.3
  auto_route: ^7.9.2

  # Local Storage
  hive: ^4.0.0
  hive_flutter: ^1.1.0
  shared_preferences: ^2.2.2
  flutter_secure_storage: ^9.0.0

  # Firebase Integration
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  cloud_firestore: ^4.13.6
  firebase_messaging: ^14.7.10
  firebase_analytics: ^10.8.0
  firebase_crashlytics: ^3.4.9
  firebase_remote_config: ^4.3.8
  firebase_storage: ^11.5.6

  # HTTP & API
  dio: ^5.4.0
  connectivity_plus: ^5.0.2
  internet_connection_checker: ^1.0.0+1

  # AI Integration
  google_generative_ai: ^0.2.2
  openai_dart: ^0.2.2
  langchain: ^0.4.2
  langchain_openai: ^0.5.1

  # Audio & Voice
  flutter_tts: ^4.0.2
  speech_to_text: ^6.6.0
  audioplayers: ^5.2.1
  just_audio: ^0.9.36
  just_audio_background: ^0.0.1-beta.11

  # Notifications
  flutter_local_notifications: ^16.3.2
  timezone: ^0.9.2
  workmanager: ^0.5.2

  # Device Integration
  device_info_plus: ^9.1.1
  package_info_plus: ^4.2.0
  health: ^10.2.0
  permission_handler: ^11.1.0
  geolocator: ^10.1.0

  # Utilities
  intl: ^0.19.0
  uuid: ^4.2.2
  equatable: ^2.0.5
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  logger: ^2.0.2+1
  flutter_dotenv: ^5.1.0
  url_launcher: ^6.2.2
  share_plus: ^7.2.2
  image_picker: ^1.0.7

  # Charts & Analytics
  fl_chart: ^0.66.2
  syncfusion_flutter_charts: ^24.1.41

  # Calendar & Time
  table_calendar: ^3.0.9
  cron: ^0.6.0

  # Theming & Localization
  flutter_localizations:
    sdk: flutter
  dynamic_color: ^1.6.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Linting & Code Quality
  flutter_lints: ^3.0.1
  very_good_analysis: ^5.1.0

  # Code Generation
  build_runner: ^2.4.7
  freezed: ^2.4.6
  json_serializable: ^6.7.1
  hive_generator: ^2.0.1
  auto_route_generator: ^7.3.2

  # Testing
  mocktail: ^1.0.2
  integration_test:
    sdk: flutter
  patrol: ^3.6.1

  # Assets
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.8

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/
    - assets/audio/
    - assets/fonts/
    - .env

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
    
    - family: NunitoSans
      fonts:
        - asset: assets/fonts/NunitoSans-Light.ttf
          weight: 300
        - asset: assets/fonts/NunitoSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/NunitoSans-SemiBold.ttf
          weight: 600

# Flutter Launcher Icons Configuration
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/healpray-icon-1024.png"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/icons/healpray-icon-1024.png"
    background_color: "#F8F9FA"
    theme_color: "#4ECDC4"
  windows:
    generate: true
    image_path: "assets/icons/healpray-icon-1024.png"
    icon_size: 48
  macos:
    generate: true
    image_path: "assets/icons/healpray-icon-1024.png"

# Native Splash Screen Configuration  
flutter_native_splash:
  color: "#F8F9FA"
  image: assets/images/healpray-splash.png
  color_dark: "#1A1A1A"
  image_dark: assets/images/healpray-splash-dark.png
  android_12:
    image: assets/images/healpray-splash-android12.png
    icon_background_color: "#4ECDC4"
    image_dark: assets/images/healpray-splash-android12-dark.png
    icon_background_color_dark: "#2C3E50"
